# Generated by Django 4.2.9 on 2024-02-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True, blank=True)),
            ],
        ),
    ]
